# Generated by Django 5.1.4 on 2025-01-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=150, verbose_name="ФИО")),
                ("bregade_number", models.IntegerField(verbose_name="Номер бригады")),
                ("salary", models.IntegerField(verbose_name="Зарплата")),
                (
                    "specialization",
                    models.CharField(max_length=50, verbose_name="Специализация"),
                ),
            ],
            options={
                "verbose_name": "Работник",
                "verbose_name_plural": "Работники",
            },
        ),
    ]
