# Generated by Django 5.1.4 on 2025-01-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worker",
            old_name="bregade_number",
            new_name="brigade_number",
        ),
    ]
